server {
    listen 80;
    server_name docs.infinitepai.com;
    return 301 https://$host$request_uri;
}


server {
    listen 443 ssl;
    server_name docs.infinitepai.com;

    include /etc/nginx/ssl/ssl.conf;
    root /usr/share/nginx/html/app-protocol;

    location / {
        try_files $uri /index.html;
        add_header Cache-Control no-cache;
        index index.html;
    }
}
